import { join, resolve } from 'node:path';
import addClasses from "rehype-class-names";
import { mdsvex, escapeSvelte } from 'mdsvex'
import shiki from 'shiki'
//import toc from "@jsdevtools/rehype-toc"
import slug from "rehype-slug"

const __dirname = resolve();

const config = {
    extensions: ['.md'],
    layout: {
        blog: "/src/lib/layouts/default.svelte",
        _: "/src/lib/layouts/default.svelte"
    },
    highlight: {
		highlighter: async (code, lang = 'text') => {
			const highlighter = await shiki.getHighlighter({ theme: 'material-theme-palenight' })
			const html = escapeSvelte(highlighter.codeToHtml(code, { lang }))
			return `{@html \`${html}\` }`
		}
	},
    rehypePlugins: [
        [slug],
        // [toc,{cssClasses: {
        //     toc: "side-nav",      // Change the CSS class for the TOC
        //     link: "nav-link",        // Change the CSS class for links in the TOC
        //   }}],
        [addClasses, {
            'a, abbr, address, area, article, aside, audio, b, base, bdi, bdo, blockquote, body, br, button, canvas, caption, cite, code, col, colgroup, data, datalist, dd, del, details, dfn, dialog, div, dl, dt, em, embed, fieldset, figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, head, header, hgroup, hr, html, i, iframe, img, input, ins, kbd, label, legend, li, link, main, map, mark, meta, meter, nav, noscript, object, ol, optgroup, option, output, p, param, picture, pre, progress, q, rp, rt, ruby, s, samp, script, section, select, small, source, span, strong, style, sub, summary, sup, svg, table, tbody, td, template, textarea, tfoot, th, thead, time, title, tr, track, u, ul, var, video, wbr': 'markdown',
            a: 'markdown-a',
            abbr: 'markdown-abbr',
            address: 'markdown-address',
            area: 'markdown-area',
            article: 'markdown-article',
            aside: 'markdown-aside',
            audio: 'markdown-audio',
            b: 'markdown-b',
            base: 'markdown-base',
            bdi: 'markdown-bdi',
            bdo: 'markdown-bdo',
            blockquote: 'markdown-blockquote',
            body: 'markdown-body',
            br: 'markdown-br',
            button: 'markdown-button',
            canvas: 'markdown-canvas',
            caption: 'markdown-caption',
            cite: 'markdown-cite',
            code: 'markdown-code',
            col: 'markdown-col',
            colgroup: 'markdown-colgroup',
            data: 'markdown-data',
            datalist: 'markdown-datalist',
            dd: 'markdown-dd',
            del: 'markdown-del',
            details: 'markdown-details',
            dfn: 'markdown-dfn',
            dialog: 'markdown-dialog',
            div: 'markdown-div',
            dl: 'markdown-dl',
            dt: 'markdown-dt',
            em: 'markdown-em',
            embed: 'markdown-embed',
            fieldset: 'markdown-fieldset',
            figcaption: 'markdown-figcaption',
            figure: 'markdown-figure',
            footer: 'markdown-footer',
            form: 'markdown-form',
            h1: 'markdown-h1',
            h2: 'markdown-h2',
            h3: 'markdown-h3',
            h4: 'markdown-h4',
            h5: 'markdown-h5',
            h6: 'markdown-h6',
            head: 'markdown-head',
            header: 'markdown-header',
            hgroup: 'markdown-hgroup',
            hr: 'markdown-hr',
            html: 'markdown-html',
            i: 'markdown-i',
            iframe: 'markdown-iframe',
            img: 'markdown-img',
            input: 'markdown-input',
            ins: 'markdown-ins',
            kbd: 'markdown-kbd',
            label: 'markdown-label',
            legend: 'markdown-legend',
            li: 'markdown-li',
            link: 'markdown-link',
            main: 'markdown-main',
            map: 'markdown-map',
            mark: 'markdown-mark',
            meta: 'markdown-meta',
            meter: 'markdown-meter',
            nav: 'markdown-nav',
            noscript: 'markdown-noscript',
            object: 'markdown-object',
            ol: 'markdown-ol',
            optgroup: 'markdown-optgroup',
            option: 'markdown-option',
            output: 'markdown-output',
            p: 'markdown-p',
            param: 'markdown-param',
            picture: 'markdown-picture',
            pre: 'markdown-pre',
            progress: 'markdown-progress',
            q: 'markdown-q',
            rp: 'markdown-rp',
            rt: 'markdown-rt',
            ruby: 'markdown-ruby',
            s: 'markdown-s',
            samp: 'markdown-samp',
            script: 'markdown-script',
            section: 'markdown-section',
            select: 'markdown-select',
            small: 'markdown-small',
            source: 'markdown-source',
            span: 'markdown-span',
            strong: 'markdown-strong',
            style: 'markdown-style',
            sub: 'markdown-sub',
            summary: 'markdown-summary',
            sup: 'markdown-sup',
            svg: 'markdown-svg',
            table: 'markdown-table',
            tbody: 'markdown-tbody',
            td: 'markdown-td',
            template: 'markdown-template',
            textarea: 'markdown-textarea',
            tfoot: 'markdown-tfoot',
            th: 'markdown-th',
            thead: 'markdown-thead',
            time: 'markdown-time',
            title: 'markdown-title',
            tr: 'markdown-tr',
            track: 'markdown-track',
            u: 'markdown-u',
            ul: 'markdown-ul',
            var: 'markdown-var',
            video: 'markdown-video',
            wbr: 'markdown-wbr',
        }],
    ],

}

export default config;